### PR TITLE
[WIP] Letsencrypt

### PR DESCRIPTION
**Pull request by mattwelborn**
I've reached the point of diminishing returns on this one. It looks like everything goes well until certbot tries to restart nginx. Maybe @dgasmith or @doaa-altarawy, your experience with nginx will resolve this issue.

```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/qcarchivecertbottest.eastus.cloudapp.azure.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/qcarchivecertbottest.eastus.cloudapp.azure.com/privkey.pem
   Your cert will expire on 2020-06-07. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

 * ERROR: nginx stopped by something else
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] still could not bind()
```
(Note that in this case, I was using the correct DNS name -- different from the one in this PR.)

### CODE REVIEW

**Comment by doaa-altarawy** [comment]
@bennybp Do you have experience with this in the BSE website?

**Comment by mattwelborn** [comment]
Here's where I am now. The certificate gets issued and passes ssl checks (https://www.ssllabs.com/ssltest/analyze.html?d=qcarchivecertbottest2.eastus.cloudapp.azure.com). However, the proxy seems to fail with a 504 error.

**Comment by mattwelborn** [comment]
Here's how certbot rewrites the nginx conf:

```
upstream app_server {
    server flask:5000;
}

server {
    server_name qcarchivecertbottest2.eastus.cloudapp.azure.com;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    client_max_body_size 64M;

    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
        gzip_static on;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_buffering off;
        proxy_redirect off;
        proxy_pass http://app_server;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/qcarchivecertbottest2.eastus.cloudapp.azure.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/qcarchivecertbottest2.eastus.cloudapp.azure.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = qcarchivecertbottest2.eastus.cloudapp.azure.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name qcarchivecertbottest2.eastus.cloudapp.azure.com;
    return 404; # managed by Certbot


}
```

**Comment by mattwelborn** [comment]
I tried running master on my VM only to find that it gives a 504 over http. This suggests that the issue is with my testing VM and not with this pull request. @doaa-altarawy would you be willing test this PR on the working VM?

**Comment by dgasmith** [comment]
Awesome! Thanks Matt.

**Pull request merged**
